// 백엔드 ErrorType의 code ({타입}_{상수}). 화면 분기에 쓰는 것만 둔다
export const ErrorCode = {
  LOGIN_FAILED: 'AUTH_LOGIN_FAILED',
  ACCOUNT_DEACTIVATED: 'AUTH_ACCOUNT_DEACTIVATED',
  UNAUTHENTICATED: 'AUTH_UNAUTHENTICATED',
  PASSWORD_CHANGE_REQUIRED: 'AUTH_PASSWORD_CHANGE_REQUIRED',
  CURRENT_PASSWORD_MISMATCH: 'AUTH_CURRENT_PASSWORD_MISMATCH',
  SAME_AS_CURRENT_PASSWORD: 'AUTH_SAME_AS_CURRENT_PASSWORD',
  HELP_REQUEST_NOT_FOUND: 'HELP_REQUEST_NOT_FOUND',
  HELP_REQUEST_INVALID_STATUS: 'HELP_REQUEST_INVALID_STATUS',
  HELP_REQUEST_NO_SHOW_PERIOD_EXPIRED: 'HELP_REQUEST_NO_SHOW_PERIOD_EXPIRED',
} as const;
